name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  ARTIFACT_DIR: ${{ github.workspace }}/dist
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  SODIUM_VERSION: "1.0.22"

jobs:
  build-linux:
    name: build (${{ matrix.rid }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            zig_target: x86_64-linux-gnu.2.17

          - rid: linux-arm64
            zig_target: aarch64-linux-gnu.2.23

          - rid: linux-arm
            zig_target: arm-linux-gnueabihf.2.23

          - rid: linux-musl-x64
            zig_target: x86_64-linux-musl

          - rid: linux-musl-arm64
            zig_target: aarch64-linux-musl

          - rid: linux-musl-arm
            zig_target: arm-linux-musleabihf

    steps:
      - name: checkout libsodium
        uses: actions/checkout@v6
        with:
          repository: jedisct1/libsodium
          ref: ${{ env.SODIUM_VERSION }}-RELEASE
          persist-credentials: false

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: latest

      - name: build (shared + static)
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.zig_target }}

          mkdir -p "${{ env.ARTIFACT_DIR }}/bin" "${{ env.ARTIFACT_DIR }}/lib"
          cp zig-out/lib/libsodium.so "${{ env.ARTIFACT_DIR }}/bin/libsodium.so"
          cp zig-out/lib/libsodium.a  "${{ env.ARTIFACT_DIR }}/lib/libsodium.a"

      - uses: actions/upload-artifact@v7
        with:
          name: libsodium-${{ matrix.rid }}
          path: ${{ env.ARTIFACT_DIR }}

  build-macos:
    name: build (osx-arm64, osx-x64)
    runs-on: macos-latest
    env:
      LIBSODIUM_FULL_BUILD: 1
      LIBSODIUM_SKIP_SIMULATORS: 1
      MACOSX_DEPLOYMENT_TARGET: "12.0"

    steps:
      - name: checkout libsodium
        uses: actions/checkout@v6
        with:
          repository: jedisct1/libsodium
          ref: ${{ env.SODIUM_VERSION }}-RELEASE
          persist-credentials: false

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: latest

      - name: configure
        run: ./configure

      - name: build (shared)
        run: ./dist-build/apple-xcframework.sh

      - name: build (static, arm64)
        run: |
          rm -fr zig-out .zig-cache
          zig build -Doptimize=ReleaseFast -Dshared=false -Dtarget=aarch64-macos

          mkdir -p "${{ env.ARTIFACT_DIR }}/osx-arm64/lib"
          cp zig-out/lib/libsodium.a "${{ env.ARTIFACT_DIR }}/osx-arm64/lib/libsodium.a"

      - name: build (static, x64)
        run: |
          rm -fr zig-out .zig-cache
          zig build -Doptimize=ReleaseFast -Dshared=false -Dtarget=x86_64-macos

          mkdir -p "${{ env.ARTIFACT_DIR }}/osx-x64/lib"
          cp zig-out/lib/libsodium.a "${{ env.ARTIFACT_DIR }}/osx-x64/lib/libsodium.a"

      - name: prepare artifacts
        run: |
          mkdir -p "${{ env.ARTIFACT_DIR }}/osx-arm64/bin" "${{ env.ARTIFACT_DIR }}/osx-x64/bin"

          cp libsodium-apple/macos/lib/libsodium.dylib "${{ env.ARTIFACT_DIR }}/osx-arm64/bin/libsodium.dylib"
          cp libsodium-apple/macos/lib/libsodium.dylib "${{ env.ARTIFACT_DIR }}/osx-x64/bin/libsodium.dylib"

      - uses: actions/upload-artifact@v7
        with:
          name: libsodium-osx-arm64
          path: ${{ env.ARTIFACT_DIR }}/osx-arm64

      - uses: actions/upload-artifact@v7
        with:
          name: libsodium-osx-x64
          path: ${{ env.ARTIFACT_DIR }}/osx-x64

  build-windows:
    name: build (win-arm64, win-x64)
    runs-on: windows-latest
    steps:
      - name: checkout libsodium
        uses: actions/checkout@v6
        with:
          repository: jedisct1/libsodium
          ref: ${{ env.SODIUM_VERSION }}-RELEASE
          persist-credentials: false

      - name: build (shared + static)
        shell: cmd
        working-directory: builds/msvc/build/
        run: buildbase.bat ..\vs2022\libsodium.sln 17

      - name: prepare artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force "${{ env.ARTIFACT_DIR }}/win-arm64/bin"
          New-Item -ItemType Directory -Force "${{ env.ARTIFACT_DIR }}/win-arm64/lib"

          New-Item -ItemType Directory -Force "${{ env.ARTIFACT_DIR }}/win-x64/bin"
          New-Item -ItemType Directory -Force "${{ env.ARTIFACT_DIR }}/win-x64/lib"

          Copy-Item "bin/ARM64/Release/v143/dynamic/libsodium.dll" "${{ env.ARTIFACT_DIR }}/win-arm64/bin/libsodium.dll"
          Copy-Item "bin/ARM64/Release/v143/static/libsodium.lib" "${{ env.ARTIFACT_DIR }}/win-arm64/lib/libsodium.lib"

          Copy-Item "bin/x64/Release/v143/dynamic/libsodium.dll" "${{ env.ARTIFACT_DIR }}/win-x64/bin/libsodium.dll"
          Copy-Item "bin/x64/Release/v143/static/libsodium.lib" "${{ env.ARTIFACT_DIR }}/win-x64/lib/libsodium.lib"

      - uses: actions/upload-artifact@v7
        with:
          name: libsodium-win-arm64
          path: ${{ env.ARTIFACT_DIR }}/win-arm64

      - uses: actions/upload-artifact@v7
        with:
          name: libsodium-win-x64
          path: ${{ env.ARTIFACT_DIR }}/win-x64

  pack:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest

    permissions:
      attestations: write
      checks: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: libsodium-*
          merge-multiple: false
          path: artifact

      - name: restore
        shell: pwsh
        run: |
          dotnet restore --locked-mode

          $artifact = Join-Path ${{ github.workspace }} "artifact"
          $output = Join-Path ${{ github.workspace }} "src"

          foreach ($runtime in @("linux-arm", "linux-arm64", "linux-x64", "linux-musl-arm", "linux-musl-arm64", "linux-musl-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64")) {
            foreach ($file in Get-ChildItem -Path ([System.IO.Path]::Combine($artifact, "libsodium-$runtime", "lib")) -Recurse -File) {
              New-Item -ItemType Directory -Path ([System.IO.Path]::Combine($output, "static", $runtime, "native")) -Force | Out-Null

              $destination = [System.IO.Path]::Combine($output, "static", $runtime, "native", $file.Name)
              Move-Item -Path $file.FullName -Destination $destination -Force

              Write-Host "[!] Moved ${file.FullName} to '$destination'"
            }

            foreach ($file in Get-ChildItem -Path ([System.IO.Path]::Combine($artifact, "libsodium-$runtime", "bin")) -Recurse -File) {
              New-Item -ItemType Directory -Path ([System.IO.Path]::Combine($output, "shared", $runtime, "native")) -Force | Out-Null

              $destination = [System.IO.Path]::Combine($output, "shared", $runtime, "native", $file.Name)
              Move-Item -Path $file.FullName -Destination $destination -Force

              Write-Host "[!] Moved ${file.FullName} to '$destination'"
            }
          }

      - name: pack
        run: dotnet build src/libsodium.nativeaot.csproj -c Release -p:LibSodiumVersion="${{ env.SODIUM_VERSION }}" && dotnet pack src/libsodium.nativeaot.csproj -c Release -o dist --no-build -p:LibSodiumVersion="${{ env.SODIUM_VERSION }}"

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: libsodium-nuget
          path: dist

  publish:
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop')

    needs: [pack]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: nuget login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          name: libsodium-nuget

      - name: push
        run: dotnet nuget push "*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
